apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: touseefhaider/client
---
kind: Service
apiVersion: v1
metadata:
  name: client-svc
spec:
  selector:
    app: client
  ports:
    - name: client
      port: 80
      targetPort: 3000
